name: Events Demo 1
on:
  pull_request:
    types:    #activity types
      - opened
  workflow_dispatch:
  push:
    branches:  #filters
      - main
      - 'dev-*' #any branch that start with dev
      - 'feat/**' #feat/new feat/new/button
    paths-ignore: #filters
      - '.github/workflows/*' #anychanges in this path would be ignored and will not be triggered
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."